version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount the project directory to the container for live code updates
      - .:/app
    environment:
      # Set environment to development to enable debug mode and auto-reloading
      - FLASK_ENV=development
      # A default secret key for development. This should be changed in production.
      - SECRET_KEY=a-secure-secret-key-for-development

    image: redis:6-alpine
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
